all: compile
	@echo -e '[INFO] Done!'

clean:
	@echo -e '[INFO] Cleaning up...'
	@find . -name "*.class" -type f -delete

compile:
	@echo -e '[INFO] Compiling the source...'
	@javac cs455/scaling/server/Server.java
	@javac cs455/scaling/client/Client.java
